"""
src/behavior/night_detector.py
================================
PURPOSE:
    Detects night-time conditions using configured operating hours
    and/or frame brightness estimation.

    When movement is detected during night hours:
        NIGHT_MOVEMENT_DETECTED

    When a person enters a restricted zone during night hours:
        NIGHT_ZONE_INTRUSION   (generated by zone_manager using this module's flag)

HOW IT WORKS (two modes, configurable):
    Mode 1 — Time-based (default):
        Compare current time against night_mode.start_time / end_time from config.
        Simple and reliable.

    Mode 2 — Brightness-based (optional):
        Calculate average pixel brightness of the frame.
        If mean brightness < brightness_threshold → night mode.

HOW TO USE:
    from src.behavior.night_detector import NightDetector

    night = NightDetector(config)
    is_night = night.is_night_time(frame=frame)   # frame is optional

    events = night.update(tracks, camera_id, frame_number, is_night)
"""

from datetime import datetime, time as dtime
from typing import List, Optional
import numpy as np

from src.tracking.track import Track
from src.events.event import AIEvent
from src.events.event_types import EventType, Severity
from src.utils.time_utils import now_ts
from src.utils.logger import get_logger

logger = get_logger(__name__)


class NightDetector:
    """
    Detects night-time conditions and generates night movement events.

    Attributes:
        enabled:              Whether night detection is active
        use_brightness:       Use frame brightness instead of time
        brightness_threshold: Mean pixel value below which = night (0-255)
        start_hour/min:       Night period start time
        end_hour/min:         Night period end time
    """

    def __init__(self, config: dict):
        """
        Initialize from config.yaml night_mode section.

        Args:
            config: Full config.yaml dictionary
        """
        night_cfg = config.get("night_mode", {})
        self.enabled: bool = night_cfg.get("enabled", True)
        self.use_brightness: bool = night_cfg.get("brightness_detection", False)
        self.brightness_threshold: int = night_cfg.get("brightness_threshold", 80)

        # Parse start/end times (e.g. "20:00" and "06:00")
        start_str = night_cfg.get("start_time", "20:00")
        end_str = night_cfg.get("end_time", "06:00")

        try:
            sh, sm = map(int, start_str.split(":"))
            eh, em = map(int, end_str.split(":"))
            self._night_start = dtime(sh, sm)
            self._night_end = dtime(eh, em)
        except Exception:
            self._night_start = dtime(20, 0)
            self._night_end = dtime(6, 0)

        # Cooldown per track for night events (seconds)
        self._cooldown: float = config.get("events", {}).get("cooldown_seconds", 10.0)
        self._last_event_time: dict = {}   # track_id → timestamp

        # Cache current night state
        self._current_night: bool = False

        logger.info(
            f"NightDetector initialized | "
            f"enabled={self.enabled} | "
            f"hours={start_str}–{end_str} | "
            f"brightness_mode={self.use_brightness}"
        )

    def is_night_time(self, frame: Optional[np.ndarray] = None) -> bool:
        """
        Determine if current conditions are night-time.

        Args:
            frame: Optional BGR frame for brightness estimation

        Returns:
            True if night conditions detected
        """
        if not self.enabled:
            return False

        if self.use_brightness and frame is not None:
            # Mode 2: brightness-based
            gray = np.mean(frame)
            is_dark = gray < self.brightness_threshold
            self._current_night = is_dark
            return is_dark

        # Mode 1: time-based
        now = datetime.now().time()
        night = self._is_in_night_window(now)
        self._current_night = night
        return night

    def _is_in_night_window(self, t: dtime) -> bool:
        """
        Check if time t falls in the night window.
        Handles overnight windows (e.g. 20:00 to 06:00).
        """
        start = self._night_start
        end = self._night_end
        if start > end:
            # Overnight: night if t >= start OR t <= end
            return t >= start or t <= end
        else:
            return start <= t <= end

    def update(
        self,
        tracks: List[Track],
        camera_id: str,
        frame_number: int,
        is_night: bool,
    ) -> List[AIEvent]:
        """
        Generate NIGHT_MOVEMENT_DETECTED events for moving objects during night.

        Args:
            tracks:       Active confirmed tracks
            camera_id:    Camera ID for events
            frame_number: Current frame number
            is_night:     Whether night mode is active this frame

        Returns:
            List of AIEvent objects
        """
        if not self.enabled or not is_night:
            return []

        events: List[AIEvent] = []
        now = now_ts()

        for track in tracks:
            if not track.is_confirmed:
                continue

            # Only fire for moving objects at night (not stationary)
            from src.tracking.track import MovementState
            if track.movement_state == MovementState.STATIONARY:
                continue

            tid = track.track_id
            last = self._last_event_time.get(tid, 0.0)
            if (now - last) < self._cooldown:
                continue

            desc = (
                f"Night-time movement detected. "
                f"{track.class_name.title()} (ID {track.track_id}) "
                f"is {track.movement_state.value.lower()} during configured night hours. "
                f"Direction: {track.direction.value}."
            )

            evt = AIEvent(
                event_type=EventType.NIGHT_MOVEMENT_DETECTED,
                camera_id=camera_id,
                severity=Severity.MEDIUM,
                track_id=track.track_id,
                object_type=track.category,
                object_class=track.class_name,
                confidence=track.confidence,
                bbox=list(track.bbox),
                center=list(track.center),
                zone_id=track.current_zone,
                movement_state=track.movement_state.value,
                direction=track.direction.value,
                pixel_speed=getattr(track, "_pixel_speed", None),
                frame_number=frame_number,
                description=desc,
                model_name="YOLOv8",
            )
            events.append(evt)
            self._last_event_time[tid] = now

        if events:
            logger.info(
                f"NIGHT MODE | {len(events)} night movement event(s) | "
                f"frame={frame_number}"
            )

        return events

    @property
    def is_active(self) -> bool:
        """Returns last computed night state (cached)."""
        return self._current_night
